const shopActionTypes = {
  GET_SHOP_COLLECTIONS_ITEMS: "GET_SHOP_COLLECTIONS_ITEMS",
  FETCH_SHOP_ITEMS_START: "FETCH_SHOP_ITEMS_START",
  FETCH_SHOP_ITEMS_SUCCEED: "FETCH_SHOP_ITEMS_SUCCEED",
  FETCH_SHOP_ITEMS_FAILURE: "FETCH_SHOP_ITEMS_FAILURE",
};

export default shopActionTypes;
